server:
  port: 8888

tomcat:
  connection-timeout: 2s
  keep-alive-timeout: 15s
  threads:
    max: 50
    min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # uri: https://github.com/git-ly/config-repo
          uri: /mnt/f/code-excercise/spring/cloud-native-spring-in-action/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}